# Generated by Django 6.0.5 on 2026-05-22 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_conteudo_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 22, 13, 50, 30, 425694, tzinfo=datetime.timezone.utc)),
        ),
    ]
