# Generated by Django 6.0.5 on 2026-05-26 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 26, 18, 51, 29, 450443, tzinfo=datetime.timezone.utc)),
        ),
    ]
