# Generated by Django 6.0.5 on 2026-05-27 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 27, 12, 11, 19, 708868, tzinfo=datetime.timezone.utc)),
        ),
    ]
