# Generated by Django 6.0.5 on 2026-06-01 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image_capa_post_resumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 1, 12, 28, 23, 511861, tzinfo=datetime.timezone.utc)),
        ),
    ]
