# Generated by Django 6.0.5 on 2026-06-17 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 17, 16, 43, 36, 223711, tzinfo=datetime.timezone.utc)),
        ),
    ]
