# Generated by Django 6.0.5 on 2026-06-17 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 17, 17, 23, 9, 5097, tzinfo=datetime.timezone.utc)),
        ),
    ]
