# Generated by Django 6.0.5 on 2026-06-18 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 18, 12, 12, 9, 86546, tzinfo=datetime.timezone.utc)),
        ),
    ]
