# Generated by Django 6.0.5 on 2026-06-18 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 18, 16, 38, 13, 19249, tzinfo=datetime.timezone.utc)),
        ),
    ]
