# Generated by Django 6.0.5 on 2026-06-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_perfil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
    ]
